name: Website Deployment (prod)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'   # match your local Ruby version
          bundler-cache: true
    
      - name: Restore Google Service Account Key
        run: |
          echo "${{ secrets.GA_SERVICE_ACCOUNT }}" > api/service-account-key.json

      - name: Build with Jekyll
        run: bundle exec jekyll build --future

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: website   # or "main" if your Pages is served from /docs on main